### ISSUE TITLE
Regarding Ringover Task

### ISSUE THREAD

**Issue by VermaShivansh** [anshu0091/13-jan-backend#1]
You were asked to use a MySQL database and not MongoDB.
Also exposing your mongodb url and key is not a good practice, please delete your .env file from here or someone else will use it.

**Comment by anshu0091** [comment]
Hello sri

**Comment by anshu0091** [comment]
> You were asked to use a MySQL database and not MongoDB. Also exposing your mongodb url and key is not a good practice, please delete your .env file from here or someone else will use it.

**Comment by anshu0091** [comment]
Hello sir due to limited time I have used a mongodb  .i was not able to
integrate my sql  due some  issue in mysql software in my system  . So due
to tight schedule i have use mongodb  if u want i can do it.

With regards
Anshu Ranjan
